MyPizzaRazorPages/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MyPizzaRazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyPizzaRazorPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyPizzaRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

MyPizzaRazorPages/Pages/Pizzas/DeletePizza.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyPizzaRazorPages.model;
using MyPizzaRazorPages.Services;

namespace MyPizzaRazorPages.Pages.Pizzas
{
    public class DeletePizzaModel : PageModel
    {
        private IPizzaService _service;

        //[BindProperty]
        public Pizza SletPizza { get; set; }

        public DeletePizzaModel(IPizzaService service)
        {
            _service = service;
        }
        public void OnGet(int id)
        {
            SletPizza = _service.FindPizza(id);
        }

        public IActionResult OnPostSlet(int id)
        {
            _service.DeletePizza(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostFortryd()
        {
            return RedirectToPage("Index");
        }

    }
}

MyPizzaRazorPages/Pages/Pizzas/EditPizza.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyPizzaRazorPages.model;
using MyPizzaRazorPages.Services;

namespace MyPizzaRazorPages.Pages.Pizzas
{
    public class EditPizzaModel : PageModel
    {
        private IPizzaService _service;

        public EditPizzaModel(IPizzaService service)
        {
            _service = service;
        }

        [BindProperty]
        public int Number { get; set; }
        [BindProperty]
        public String Name { get; set; }
        [BindProperty]
        public String Description { get; set; }
        [BindProperty]
        public double Price { get; set; }
        [BindProperty]
        public bool IsVegan { get; set; }
        [BindProperty]
        public bool DeepPan { get; set; }
     
        
        public void OnGet(int id)
        {
            Pizza editPizza = _service.FindPizza(id);

            Number = editPizza.Number;
            Name = editPizza.Name;
            Description = editPizza.Description;    
            Price = editPizza.Price;
            IsVegan = editPizza.IsVegan;
            DeepPan = editPizza.DeepPan;

        }



        public IActionResult OnPostEdit(int id)
        {
            Pizza newValues = new Pizza(id, Name, Description, Price, IsVegan, DeepPan);

            _service.EditPizza(newValues);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostFortryd()
        {
            return RedirectToPage("Index");
        }
    }
}

MyPizzaRazorPages/Pages/Pizzas/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyPizzaRazorPages.mockData;
using MyPizzaRazorPages.model;
using MyPizzaRazorPages.Services;

namespace MyPizzaRazorPages.Pages.Pizzas
{
    public class IndexModel : PageModel
    {
        private IPizzaService _service;

        public IndexModel(IPizzaService service)
        {
            _service = service;
        }

        // Property til at vise pizzaer
        public List<Pizza> Pizzaer { get; set; }

        public void OnGet()
        {
            //MockPizzaListe mock = new MockPizzaListe();
            Pizzaer = _service.GetAllPizzas();
        }
    }
}

MyPizzaRazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyPizzaRazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyPizzaRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyPizzaRazorPages/Pages/Pizzas/CreatePizza.cshtml
@page
@model MyPizzaRazorPages.Pages.Pizzas.CreatePizzaModel
@{
}
<h1>Opret en ny Pizza</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Pizza.Number" class="control-label">Nummer</label><br>
                <input asp-for="@Model.Pizza.Number" class="form-control" /><br>
            </div>

            <div class="form-group">
                <label>Navn</label><br>
                <input asp-for="@Model.Pizza.Name" class="form-control" /><br />
            </div>

            <div class="form-group">
                <label>Beskrivelse</label><br>
                <input asp-for="@Model.Pizza.Description" class="form-control" /><br />
            </div>

            <div class="form-group">
                <label>Pris</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Vegansk</label><br>
                <input asp-for="@Model.Pizza.IsVegan" class="form-control" /><br />
            </div>

            <div class="form-group">
                <label>DeepPan</label><br>
                <input asp-for="@Model.Pizza.DeepPan" class="form-control" /><br />
            </div>

            <div class="form-group">
                <input type="submit" value="Opret Pizza" />
            </div>

        </form>
    </div>
</div>

MyPizzaRazorPages/Pages/Pizzas/DeletePizza.cshtml
@page
@model MyPizzaRazorPages.Pages.Pizzas.DeletePizzaModel
@{
}
<h1>Vil du slette</h1>

<p>Nummer:  @Model.SletPizza.Number</p>
<p>Navn:    @Model.SletPizza.Name</p>
<p>Beskrivelse:  @Model.SletPizza.Description</p>
<p>Pris:  @Model.SletPizza.Price</p>
<p>Type:  @Model.SletPizza.Type</p>
<p>Vegansk:  @Model.SletPizza.IsVegan</p>
<p>DeepPan:  @Model.SletPizza.DeepPan</p>
<p></p>
<form method="post">
    <div class="form-group">
        <input type="submit" value="Slet Pizza" asp-page-handler="Slet" asp-route-id="@Model.SletPizza.Number" class="btn btn-danger" />
    </div>
    <div class="form-group">
        <input type="submit" value="Fortryd" asp-page-handler="Fortryd" class="btn btn-primary"/>
    </div>
</form>

MyPizzaRazorPages/Pages/Pizzas/EditPizza.cshtml
@page
@model MyPizzaRazorPages.Pages.Pizzas.EditPizzaModel
@{
}
<h1>Ændre Pizza nummer @Model.Number @Model.Name</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <input type="hidden" asp-for="@Model.Number" class="form-control" /><br>
            </div>

            <div class="form-group">
                <label>Navn</label><br>
                <input asp-for="@Model.Name" class="form-control" /><br />
            </div>

            <div class="form-group">
                <label>Beskrivelse</label><br>
                <input asp-for="@Model.Description" class="form-control" /><br />
            </div>

            <div class="form-group">
                <label>Pris</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Vegansk</label><br>
                <input asp-for="@Model.IsVegan" /><br />
            </div>

            <div class="form-group">
                <label>DeepPan</label><br>
                <input asp-for="@Model.DeepPan" /><br />
            </div>

            <form method="post">
                <div class="form-group">
                    <input type="submit" value="Edit Pizza" asp-page-handler="Edit" asp-route-id="@Model.Number" class="btn btn-success" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Fortryd" asp-page-handler="Fortryd" class="btn btn-primary" />
                </div>
            </form>

        </form>
    </div>
</div>

MyPizzaRazorPages/Pages/Pizzas/Index.cshtml
@page
@model MyPizzaRazorPages.Pages.Pizzas.IndexModel
@{
}
<h1>Hej dette er Pizza siden</h1>

<table class="table table-hover">
    <thead>
        <tr>
        <th>Nummer</th>
        <th>Navn</th>
        <th>Beskrivelse</th>
        <th>Pris</th>
        <th>Vegansk</th>
        <th>DeepPan</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.Pizzaer)
        {
            <tr>
                <td>@p.Number</td>
                <td>@p.Name</td>
                <td>@p.Description</td>
                <td>@p.Price</td>
                <td>@p.IsVegan</td>
                <td>@p.DeepPan</td>

                <td><a asp-page="DeletePizza" asp-route-id="@p.Number">Delete</a></td>
                 | 
                <td><a asp-page="EditPizza" asp-route-id="@p.Number">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

<p>Hvis du vil oprette en ny pizza følg link</p>
<a asp-page="CreatePizza">Opret Pizza</a> 

    

MyPizzaRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyPizzaRazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPizzaRazorPages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyPizzaRazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Pizzas/Index">Pizza</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyPizzaRazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>